// Real Chromium WebGL integration, with controlled fixtures for every mechanic.
// The capture and pilot suites separately exercise user input and full routes.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'}),page=await browser.newPage({viewport:{width:1280,height:800}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.goto('http://127.0.0.1:4177/?test');await page.waitForFunction(()=>!!window.skyrail?.game);await page.locator('[data-action="start"]').first().click();await page.waitForTimeout(200);
 await page.keyboard.press('KeyE');await page.waitForTimeout(2000);assert.equal((await page.evaluate(()=>skyrail.snapshot())).rope,null,'Pull reaches the train');
 const results=await page.evaluate(async()=>{
  const g=skyrail.game,Vec=g.player.position.constructor,out=[];g.pause();
  const test=(name,fn)=>{try{const details=fn();out.push({name,pass:true,details});}catch(e){out.push({name,pass:false,message:e.stack});}};
  const check=(value,message)=>{if(!value)throw Error(message);};
  const fixture=()=>{g.mode='playing';g.intro=false;g.world.build(0,'iron',171);g.clearEnemies();g.combat.weaponIndex=0;g.mods={};g.combat.reset();g.player.mod=g.mods;g.maxHealth=g.health=100;g.invulnerability=0;g.time=0;g.player.reset(g.world.start.pos.clone().add(new Vec(0,0,0)),g.world.start);g.yaw=0;g.pitch=0;g.camera.position.copy(g.player.position).add(new Vec(0,4,10));g.camera.lookAt(g.player.position.clone().add(new Vec(0,1,-15)));g.keys.clear();g.pressed.clear();};
  test('Every weapon consumes ammo, applies damage and reloads',()=>{fixture();const damages=[];for(let i=0;i<5;i++){const enemy=g.combat.enemies.find(e=>!e.dead);enemy.position.copy(g.player.position).add(new Vec(0,0,-13));enemy.shield=false;enemy.hp=enemy.maxHp=1000;enemy.mesh.position.copy(enemy.position);g.camera.lookAt(enemy.position.clone().add(new Vec(0,1.05,0)));g.camera.updateMatrixWorld();g.combat.switch(i);g.combat.cooldown=0;const before=enemy.hp,ammo=g.combat.ammo[i];check(g.combat.fire(),'weapon '+i+' failed');check(g.combat.ammo[i]===ammo-1,'ammo');check(enemy.hp<before,'damage '+i);damages.push(before-enemy.hp);g.combat.reload();for(let j=0;j<300;j++)g.combat.update(1/120);check(g.combat.ammo[i]===g.combat.capacity,'reload '+i);}return damages;});
  test('Six grapple modes affect movement, shields and attachments',()=>{fixture();const a=g.world.anchors[0];for(const mode of ['PULL','SWING','SLINGSHOT']){g.player.reset(new Vec(-12,8,18));g.player.attach(a,mode);check(g.player.rope.mode===mode,'attach '+mode);for(let i=0;i<25;i++){g.world.tick(i/120,1/120);g.player.step(1/120,{x:0,z:-1},g.world.bodies);}if(mode==='SLINGSHOT'){const speed=g.player.speed;g.player.release(true,new Vec(0,.2,-1));check(g.player.speed>speed,'slingshot impulse');}g.player.release();}g.player.reset(new Vec(0,0,0),g.world.start);g.forward.set(0,0,-1);const e=g.combat.enemies.find(e=>e.shield);e.position.set(0,0,-8);e.hp=1000;check(g.combat.grappleEnemy('RIP'),'rip');check(!e.shield,'shield removed');check(g.combat.grappleEnemy('DRAG'),'drag');check(e.velocity.length()>0,'drag impulse');check(g.combat.grappleEnemy('LINK'),'link');check(e.linked,'link attachment');});
  test('Fuel explosions damage nearby enemy and award cache reward',()=>{fixture();const fuel=g.world.targets.find(t=>t.type==='fuel'),enemy=g.combat.enemies[0];enemy.position.copy(fuel.world).add(new Vec(2,0,0));enemy.shield=false;enemy.hp=200;g.combat.damageTarget(fuel,99);check(fuel.dead,'fuel');check(enemy.hp<200,'explosion');const cache=g.world.targets.find(t=>t.reward&&!t.secret),scrap=g.save.scrap;g.combat.damageTarget(cache,99);check(g.save.scrap>scrap,'cache');});
  test('Sector locks block departure and upgrades branch to new biome',()=>{fixture();g.player.position.copy(g.world.end.pos);g.interact();check(g.mode==='playing'&&g.sector===0,'locked gate');for(const t of g.world.objectives())g.combat.damageTarget(t,999);const elite=g.combat.enemies.find(e=>e.elite);g.combat.damageEnemy(elite,9999);g.interact();check(g.mode==='upgrades','upgrade selection');g.chooseUpgrade('long_line');check(g.mods.long_line&&g.mode==='routes','upgrade effect');g.chooseRoute('cloud');check(g.sector===1&&g.biome==='cloud'&&g.mode==='playing','new route');check(g.world.objectives().length===3,'new locks');});
  test('Persistent workshop spends salvage and modifies next run',()=>{fixture();g.save.scrap=1000;g.save.workshop={};g.buyWorkshop('armor');g.buyWorkshop('engine');g.buyWorkshop('magazine');g.buyWorkshop('medbay');check(g.save.scrap===610,'four prices');g.launchSector(false);check(g.maxHealth===115,'armor applied');check(g.combat.capacity===27,'magazine applied');g.health=80;g.player.position.y=-50;g.rescue();check(g.health===72,'medbay rescue cost');});
  test('Three boss phases unlock in order, extraction wins, checkpoint clears',()=>{g.sector=4;g.biome='storm';g.mods={};g.launchSector(false);const locked=g.world.targets.find(t=>t.phase===3);g.combat.damageTarget(locked,9999);check(!locked.dead,'future phase protected');for(let phase=1;phase<=3;phase++){check(g.bossPhase===phase,'phase '+phase);for(const t of g.world.targets.filter(t=>t.phase===phase))g.combat.damageTarget(t,9999);}check(g.extractionReady,'extraction unlocked');g.player.position.copy(g.world.extraction.pos);g.player.grounded=false;g.player.support=null;g.interact();check(g.mode==='playing','airborne extraction rejected');g.player.reset(g.world.extraction.pos,g.world.extraction);g.interact();check(g.mode==='victory','victory');check(g.save.checkpoint===null,'checkpoint cleared');});
  test('Retry clears movement transients, menu cleans actors and preserves save',()=>{g.sector=0;g.biome='iron';g.launchSector(false);g.player.slideTime=1;g.player.dashTime=1;g.launchSector(false);check(!g.player.slideTime&&!g.player.dashTime,'transients');g.menu();check(g.combat.enemies.length===0&&!g.hero.visible,'menu clean');check(g.save.wins>0,'win preserved');});
  test('Thin cover blocks hitscan and travelling projectiles',()=>{fixture();g.clearEnemies();const b=g.world.start,o={x:0,z:-1.15,width:1.6,depth:1.6,height:1.7};b.obstacles.push(o);const from=new Vec(0,1.35,0),to=new Vec(0,1.05,-5.9);check(!g.combat.lineClear(from,to),'thin cover blocks');check(g.combat.lineClear(from,to,o),'selected target may be hit');g.combat.bullets.push({pos:from.clone(),velocity:new Vec(0,0,-36),life:3,damage:8});g.combat.update(.04);check(g.combat.bullets.length===0,'projectile stopped by cover');o.broken=true;check(g.combat.lineClear(from,to),'broken cover clears ray');});
  test('Upward aim reaches elevated targets and shake zero is respected',()=>{fixture();g.pitch=-1;g.settings.cameraShake=0;g.cameraUpdate(.016);const dir=g.camera.getWorldDirection(new Vec());check(dir.y>.8,'upward aim over 50 degrees');g.pitch=1;g.cameraUpdate(.016);check(g.camera.getWorldDirection(new Vec()).y<-.8,'downward aim');});
  test('Intro always boards in PULL mode and banked scrap survives menu',()=>{fixture();g.intro=true;g.hookMode=4;g.hookCooldown=0;g.useHook();check(!g.intro&&g.player.rope?.mode==='PULL','combat mode cannot strand glider');const before=g.save.scrap;g.onKill({elite:false});g.menu();const stored=JSON.parse(localStorage.getItem('skyrail-save-v1'));check(stored.scrap===before+9,'bank survives menu/reload');});
  test('Small environmental objects can be dragged and linked',()=>{fixture();g.clearEnemies();const fuel=g.world.targets.find(t=>t.type==='fuel');g.player.reset(fuel.world.clone().add(new Vec(0,0,4)),fuel.body);g.hookMode=3;g.hookCooldown=0;g.useHook();check(fuel.loose?.length()>0,'DRAG object impulse');g.hookMode=5;g.hookCooldown=0;g.useHook();check(fuel.link?.body!==fuel.body,'LINK moving body');});
  return out;
 });
 console.log(JSON.stringify({results,errors},null,2));fs.mkdirSync(path.join(__dirname,'../test-results'),{recursive:true});fs.writeFileSync(path.join(__dirname,'../test-results/integration.json'),JSON.stringify({results,errors},null,2));await browser.close();assert.equal(errors.length,0,'No browser errors');assert.ok(results.every(r=>r.pass),'All game integration scenarios');
})().catch(e=>{console.error(e);process.exitCode=1;});
